// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDim7xFFhsRZvoXxt7_Ltw9NAwYiP-3Vo',
    appId: '1:960359090113:web:d4cc25c1520b8de7175140',
    messagingSenderId: '960359090113',
    projectId: 'medicalhistory-5d275',
    authDomain: 'medicalhistory-5d275.firebaseapp.com',
    storageBucket: 'medicalhistory-5d275.firebasestorage.app',
    measurementId: 'G-JKVB0VF7C5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUVE9VzA4VaraOqxeEkAmue8_wrpL3I08',
    appId: '1:960359090113:android:a144a15716f997b5175140',
    messagingSenderId: '960359090113',
    projectId: 'medicalhistory-5d275',
    storageBucket: 'medicalhistory-5d275.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR5cIKsNjlIkZ88z8nOHDyCEQ6_Wm83vg',
    appId: '1:960359090113:ios:3d8ad58bb94f549f175140',
    messagingSenderId: '960359090113',
    projectId: 'medicalhistory-5d275',
    storageBucket: 'medicalhistory-5d275.firebasestorage.app',
    iosBundleId: 'com.example.medhistory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR5cIKsNjlIkZ88z8nOHDyCEQ6_Wm83vg',
    appId: '1:960359090113:ios:3d8ad58bb94f549f175140',
    messagingSenderId: '960359090113',
    projectId: 'medicalhistory-5d275',
    storageBucket: 'medicalhistory-5d275.firebasestorage.app',
    iosBundleId: 'com.example.medhistory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDim7xFFhsRZvoXxt7_Ltw9NAwYiP-3Vo',
    appId: '1:960359090113:web:81d3ffa6e62b6174175140',
    messagingSenderId: '960359090113',
    projectId: 'medicalhistory-5d275',
    authDomain: 'medicalhistory-5d275.firebaseapp.com',
    storageBucket: 'medicalhistory-5d275.firebasestorage.app',
    measurementId: 'G-X5SXYLWV5Q',
  );
}
